### ISSUE TITLE
TypeError when trying to add an organizer or location to existing calendarize_event record

### ISSUE THREAD

**Issue by artus70** [andreaskastl/calendarize_address#1]
Installation of calendarize_address was fine, tables where created, but ...

When trying to add one or more organizer or location to an existing calendarize_event record, after hitting the save button, this error message appears:

```
1/1) TypeError

Argument 2 passed to TYPO3\CMS\Core\DataHandling\Localization\State::__construct() must be of the type array, int given, called in [my path]/htdocs/typo3_src-10.4.13/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3441
```

What am I doing wrong? Any further information needed?

![grafik](https://user-images.githubusercontent.com/367315/110974232-9aab1580-835e-11eb-92a9-583478b3b857.png)

**Comment by andreaskastl** [comment]
Please provide further details:
- versions used for calendarize and calendarize_address?
- full stack trace: where in the calendarize_address code does the error seem to occur?
- was an upgrade of calendarize_address performed / was an older version used previously?
- clear the cache in backend under admin tools => Flush Typo3 and PHP cache and rebuild autoload information 
- try again and send further information if the error still exists

**Comment by sypets** [comment]
The problem was due to tx_calendarize_domain_model_event.l10n_state set to 0 in some events. This was due to incomplete migration and manually incorrectly fixing on a test system. Should be ok now.

Issue can be closed.

---

(l10n_state in DB schema is TEXT and default NULL, should be either NULL or empty string but not 0 )(int), hence the error.

**Comment by andreaskastl** [comment]
Issue closed. Thanks to @sypets
