### ISSUE TITLE
Support for latest calendarize ^9.0.0?

### ISSUE THREAD

**Issue by sypets** [andreaskastl/calendarize_address#2]
in composer.json / ext_emconf.php

https://github.com/lochmueller/calendarize/releases

**Note**: This calendarize version dropped PHP 7.2 support so this would be breaking.

**Comment by sypets** [comment]
To clarify: I am already using

* calendarize 9.0.0
* calendarize_address: 1.2.0

but had to add branch alias in composer.json because calendarize_address depends on 8 or 7 of calendarize. The version 9 is fairly new.

**Comment by andreaskastl** [comment]
Thanks for the hint @sypets.
I updated the dependencies and released version 1.3.0. https://github.com/andreaskastl/calendarize_address/releases/tag/1.3.0
Please validate if composer.json works correctly.

**Comment by sypets** [comment]
That was fast. Thanks.

Validated: After updating calendarize_addresse, calendarize can be updated to 9.0.0 without tweaking.
