### ISSUE TITLE
Support for calendarize 10.0.0?

### ISSUE THREAD

**Issue by sypets** [andreaskastl/calendarize_address#4]

**Comment by andreaskastl** [comment]
Thanks @sypets for the pull request #5 and sorry for the late reply.

Info: 
- Extension is generally compatible with calendarize 10.x.
- There seem to be some issues remaining with new pagination implementation of 10.x in location or organizer view. 
- Both views use the calendarize default list partial with related pagination. Pagination does not work in location or organizer view with currentPage > 1 (organizer resp. location missing). I will fix this later.
- As a workaround please disable pagniation in location and organizer view.

**Comment by sypets** [comment]
Thank you!

**Comment by andreaskastl** [comment]
Compatiblity with calendarize 10 solved, see release 2.0.0.
