### ISSUE TITLE
Broken links in pagination

### ISSUE THREAD

**Issue by vigri** [andreaskastl/calendarize_address#7]
**Environment:**
Typo3: `10.4 LTS`
calendarize_address: `dev-main`

Hi there,

I've installed `calendarize_address` and setup some test-locations and events.
Everything works fine except the pagination when I open a location.

The related events are all shown. However, when I click on a page number I get `No location specified or found.`

This is what the link looks like for a specific location:
`https://example.com/termine/veranstaltungsort/locationABC`

This is what the link in the pagination looks like:
`https://example.com/termine/veranstaltungsort?tx_calendarize_location[controller]=Address&tx_calendarize_location[currentPage]=2&cHash=94f7c9d325704c5480390e09d95fe323`

It seems to me, that there is a parameter for the "current" location missing.

Debug-output for `pagination`
![image](https://user-images.githubusercontent.com/2580723/135765531-b5b24ee4-0a9e-4712-a518-266cdd0bedcb.png)

Is this a bug or am I missing something?

Thanks in advance.

**Comment by andreaskastl** [comment]
Hi @vigri,

please check your custom templates and partials and adapt if needed:
1) The pagination partial provided by calendarize_address overwrites the default calendarize pagination partial and adds location and organizer references for specific location resp. organizer if defined. For example in https://github.com/andreaskastl/calendarize_address/blob/5e5c22c95c9071f0f7156658feb01ac409a48bc8/Resources/Private/Partials/Pagination.html#L29 the following arguments are added to the `uri:action` method: `location: location, organizer: organizer`.
2) The location template includes in `events` section the reference to pagination partial with location reference `location: address`. Example: https://github.com/andreaskastl/calendarize_address/blob/5e5c22c95c9071f0f7156658feb01ac409a48bc8/Resources/Private/Templates/Address/Location.html#L151

Regards
Andreas

**Comment by vigri** [comment]
Hi @andreaskastl 

your first hint did the trick. I've overwritten the pagination with a custom template which was derived from the original one. As a result, the new parameters were missing.

Everything is working fine now. Thank you very much!
