### ISSUE TITLE
Can you tag a new version please, for calendarize 11 support?

### ISSUE THREAD

**Issue by sypets** [andreaskastl/calendarize_address#8]
The current master / main supports calendarize 11 and 12, but the latest tag is [2.0.0](https://github.com/andreaskastl/calendarize_address/releases/tag/2.0.0) which does not support calendarize 11.

This way, one can use the official version again.

I am not sure, if support for calendarize v12 has been tested thoroughly. I use calendarize_address with calenderarize v11 without problems.

**Comment by andreaskastl** [comment]
Done, see here: [3.0.0](https://github.com/andreaskastl/calendarize_address/releases/tag/3.0.0)
Please continue to test with calendarize v11 and v12 and report any issues.
